server:
  port: 8448

spring:
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 5f38e9747dc301
    password: a5d998f9c7ffaa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#            // Looking to send emails in production? Check out our Email API/SMTP product!
#            play.mailer {
#            host = "sandbox.smtp.mailtrap.io"
#            port = 2525
#            ssl = no
#            tls = yes
#            user = "5f38e9747dc301"
#            password = "a5d998f9c7ffaa"
#        }

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/edunest
    username: edunest
    password: edunest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 jour en millisecondes
      refresh-token:
        expiration: 604800000 # 7 jours en millisecondes

logging:
  level:
    org.springframework: DEBUG
#    org.hibernate: DEBUG
#    org.postgresql: DEBUG
#    liquibase: DEBUG
